
MAZE_HEIGHT = 50
MAZE_WIDTH = 50

CELL_SIZE = 10

CURRENT_CELL_COLOR = "#1E5128"
VISITED_CELL_COLOR = "#D8E9A8"
WAY_CELL_COLOR = "#FFFFFF"

WALL_LINE_COLOR = "#4E9F3D"
WALL_LINE_THICKNESS = 1

CLOCK_TICK = 100

screen_height = MAZE_HEIGHT * CELL_SIZE
screen_width = MAZE_WIDTH * CELL_SIZE