
MAZE_HEIGHT = 10
MAZE_WIDTH = 10

CELL_SIZE = 70
WALL_LINE_THICKNESS = 3

CURRENT_CELL_COLOR = "forestgreen"
VISITED_CELL_COLOR = "darkolivegreen1"
WAY_CELL_COLOR = "white"
WALL_LINE_COLOR = "green"

CLOCK_TICK = 5

screen_height = MAZE_HEIGHT * CELL_SIZE
screen_width = MAZE_WIDTH * CELL_SIZE


